### ISSUE TITLE
Max height for project excerpt?

### ISSUE THREAD

**Issue by jsarchibald** [GSE-CCL/getting-unstuck-web#103]
Some of these do get really long. Shouldn't be difficult to max height the container and overflow auto

**Comment by jsarchibald** [comment]
For reference:

![image](https://user-images.githubusercontent.com/43184986/86501968-18e50000-bd6c-11ea-9e5d-d4bcead7960d.png)

**Comment by paulinahaduong** [comment]
I was noticing that too! Could we cut it to half that size?

**Comment by azhou4** [comment]
@jsarchibald was this ever fixed?

**Comment by jsarchibald** [comment]
@azhou4 not yet

**Comment by jsarchibald** [comment]
@azhou4 currently working on this

**Comment by jsarchibald** [comment]
Max height 500px
