### ISSUE TITLE
username lookup - remove case sensitivity

### ISSUE THREAD

**Issue by paulinahaduong** [GSE-CCL/getting-unstuck-web#104]
Just in case people misremember their usernames

**Comment by jsarchibald** [comment]
Currently working on this @azhou4

**Comment by jsarchibald** [comment]
Finished, will be in my next PR -- as proof:
![image](https://user-images.githubusercontent.com/43184986/86556211-aa956e80-bf20-11ea-9bd1-ff5bceb7795b.png)
