### ISSUE TITLE
Font size! 1 rem all the way across?

### ISSUE THREAD

**Issue by paulinahaduong** [GSE-CCL/getting-unstuck-web#105]
Homepage: change from .9rem to 1rem

Sorry Amy! We went back + forth and changed our mind. Just change the splash page so it's consistent with everything else now? Thanks!

**Comment by azhou4** [comment]
https://github.com/GSE-CCL/getting-unstuck-web/commit/e25fbe652bedde35dd89edda199526f85725abad
