### ISSUE TITLE
Spacing

### ISSUE THREAD

**Issue by paulinahaduong** [GSE-CCL/getting-unstuck-web#106]
Could you adjust the spacing between the question + the checkboxes? Thank you! 
<img width="378" alt="Screenshot 2020-06-30 14 27 18" src="https://user-images.githubusercontent.com/5756274/86163154-d908e900-badd-11ea-98ae-ac4992a2deae.png">
<img width="403" alt="Screenshot 2020-06-30 14 27 24" src="https://user-images.githubusercontent.com/5756274/86163155-d908e900-badd-11ea-834a-596b5436f1bf.png">

**Comment by azhou4** [comment]
https://github.com/GSE-CCL/getting-unstuck-web/commit/e0311cc8805eecc68d008120431029295edf6d6c
