### ISSUE TITLE
Update slider based on meeting discussion

### ISSUE THREAD

**Issue by paulinahaduong** [GSE-CCL/getting-unstuck-web#117]
- [x] start w/ smaller amounts + rounding amounts (nearest 30? 50?) 

- [x] change label to hours after 120 minutes 

- [x] Limit to 180 minutes 

- [x] 181 minutes = 3+ hours 

- [x] being able to change it if possible 

- [x] change the question to "How many minutes did you spend working on this project?"

**Comment by jsarchibald** [comment]
Related to #102

**Comment by jsarchibald** [comment]
Done on the working branch, will merge to master once other parts complete.
