### ISSUE TITLE
Prompts page: replace link to studio schema page w/ the email link

### ISSUE THREAD

**Issue by paulinahaduong** [GSE-CCL/getting-unstuck-web#122]
Upon further reflection, we're trying to simplify the workflow (and prioritize access to subscribers), so let's hide this link for now + change this to "See the email" + add that email link to the schema. Thank you! 

(it's fine to leave it publicly accessible w/ the URL if needed for now; maybe it'll be useful later!)

**Comment by jsarchibald** [comment]
Resolved by #124
