### ISSUE TITLE
Reduce size of the prompt text

### ISSUE THREAD

**Issue by paulinahaduong** [GSE-CCL/getting-unstuck-web#131]
Let's make the prompt text the same size as the rest of the body text? 

<img width="746" alt="Screenshot 2020-07-05 18 15 11" src="https://user-images.githubusercontent.com/5756274/86543386-f679f080-beeb-11ea-8bf3-81aecdb3a3fd.png">

**Comment by jsarchibald** [comment]
Still indented?

**Comment by paulinahaduong** [comment]
I've just been playing around with it, and let's do the following:

- [ ] yes indent
- [ ] font-weight: 600;
- [ ] For the "how you used the "when flag clicked" block --> let's make that also font-weight: 600. (600 is less than "bolder" it looks like)

Thanks!

**Comment by azhou4** [comment]
https://github.com/GSE-CCL/getting-unstuck-web/commit/6172a53a2abaec3c7eb5ac029e842870a6ff9775

**Comment by paulinahaduong** [comment]
Is this closed but the changes just haven't been pushed yet? (looking at the font-weight for the prompt and for the "when green flag clicked")

**Comment by paulinahaduong** [comment]
@azhou4 if you could check the centering that would be good too!

<img width="1144" alt="Screenshot 2020-07-06 16 51 03" src="https://user-images.githubusercontent.com/5756274/86641135-e8d67080-bfa8-11ea-88ed-ed434417e1c2.png">

**Comment by azhou4** [comment]
ok should be fixed now! https://github.com/GSE-CCL/getting-unstuck-web/commit/214328a3fe78a892eff1bdc1102618d2e29c84c0
