### ISSUE TITLE
total number projects >> "projects in the studio"

### ISSUE THREAD

**Issue by paulinahaduong** [GSE-CCL/getting-unstuck-web#132]
<img width="719" alt="Screenshot 2020-07-05 18 33 03" src="https://user-images.githubusercontent.com/5756274/86543587-0b578380-beee-11ea-9897-7635e7166e88.png">

**Comment by jsarchibald** [comment]
This won't be possible right now. This text is autogenerated based on how the stats are stored in the database, and adding exceptions isn't feasible before release time.

**Comment by paulinahaduong** [comment]
@jsarchibald can we change the label of the stat? The other two aren't ideal (total block count) but it's okay; the "total number projects" is just grammatically incorrect...

**Comment by jsarchibald** [comment]
Certainly that can be changed later this week but probably won't be done for tomorrow

**Comment by azhou4** [comment]
I second that -- looked at the schema, then looked at the way the code is set up. There's not an intuitive, fast solution
