### ISSUE TITLE
equal space above/below the stats

### ISSUE THREAD

**Issue by paulinahaduong** [GSE-CCL/getting-unstuck-web#134]
There' smore space below than above right now; can we add more space above the numbers?

<img width="719" alt="Screenshot 2020-07-05 18 33 03" src="https://user-images.githubusercontent.com/5756274/86543601-25916180-beee-11ea-8cc1-d049d2da7f98.png">

**Comment by azhou4** [comment]
https://github.com/GSE-CCL/getting-unstuck-web/commit/dd882a23c54dce6393572184b86a25cf6ed53a7b
