### ISSUE TITLE
Move the social media buttons

### ISSUE THREAD

**Issue by paulinahaduong** [GSE-CCL/getting-unstuck-web#135]
They're just sort of hanging out in space right now...can we reduce the amount of space below "share"/"tweet" and the footer? 

<img width="750" alt="Screenshot 2020-07-05 18 35 03" src="https://user-images.githubusercontent.com/5756274/86543610-3f32a900-beee-11ea-8164-a7c955f1848b.png">

**Comment by azhou4** [comment]
https://github.com/GSE-CCL/getting-unstuck-web/commit/dd882a23c54dce6393572184b86a25cf6ed53a7b
