### ISSUE TITLE
Prompts page updates

### ISSUE THREAD

**Issue by paulinahaduong** [GSE-CCL/getting-unstuck-web#144]
- [ ] Make the number smaller (left side of the table)

- [ ] Change "sign up for the mailing list" to point you to /signup

<img width="1299" alt="Screenshot 2020-07-06 10 00 41" src="https://user-images.githubusercontent.com/5756274/86602678-00920280-bf71-11ea-88b2-00b423f2d712.png">

**Comment by azhou4** [comment]
<img width="1434" alt="Screen Shot 2020-07-06 at 7 35 02 pm" src="https://user-images.githubusercontent.com/31658336/86667602-cc91fe00-bfbf-11ea-8dc3-a33d799511dd.png">
Added sign up link. Super weird that the table looks like that on the prod server when my master branch local copy (updated) looks correct? @jsarchibald any ideas why this could be?

**Comment by jsarchibald** [comment]
@azhou4 There are `th` tags in the rows with scope row. They're unneeded; try changing them to `td` tags and removing all the attributes that they had (role, colspan). Then add class "p-3" for padding and "align-middle" for vertical align middle. Also, `tbody` is unneeded unless there's a `thead` to go with it.

**Comment by azhou4** [comment]
Fixed! Thanks :) 
https://github.com/GSE-CCL/getting-unstuck-web/commit/4d70fef807c8a0cfa38dad2aaf0abac16206b677
