### ISSUE TITLE
Prompts page - awareness of the viz tool

### ISSUE THREAD

**Issue by paulinahaduong** [GSE-CCL/getting-unstuck-web#145]
Change "Learn more about what you’ve made here." >> to be a centered button (same light blue button w/ white text) that says "What did you make? What did you learn?"

<img width="1299" alt="Screenshot 2020-07-06 10 00 41" src="https://user-images.githubusercontent.com/5756274/86602914-55ce1400-bf71-11ea-98e0-6b06bb7d02f1.png">

**Comment by azhou4** [comment]
<img width="1436" alt="Screen Shot 2020-07-06 at 7 28 54 pm" src="https://user-images.githubusercontent.com/31658336/86666949-21814480-bfbf-11ea-8ed5-656a31de4cf1.png">
@paulinahaduong Feeling pretty confident but still wanted to check: I think I should delete "Already participating in Getting Unstuck" too, right? Could I also get the link for signing up for the mailing list (or should that just point to the Sign Up page)?
