### ISSUE TITLE
Prompts page

### ISSUE THREAD

**Issue by paulinahaduong** [GSE-CCL/getting-unstuck-web#147]
- [ ] Add the link to the public studio page to each schema/prompt, make it appear as "Explore what you made" between "See the email" and "Explore the Scratch studio"
- [ ] Left align the links, add something (a pipe?) in between.

<img width="1299" alt="Screenshot 2020-07-06 10 00 41" src="https://user-images.githubusercontent.com/5756274/86603535-1bb14200-bf72-11ea-9bcc-e88c3470eec8.png">

**Comment by azhou4** [comment]
<img width="1436" alt="Screen Shot 2020-07-06 at 7 28 54 pm" src="https://user-images.githubusercontent.com/31658336/86666794-f860b400-bfbe-11ea-8c36-809dcc118730.png">
https://github.com/GSE-CCL/getting-unstuck-web/commit/002a271efa771ff14d4b5150d68e7520c09b7876
