### ISSUE TITLE
User's projects page

### ISSUE THREAD

**Issue by paulinahaduong** [GSE-CCL/getting-unstuck-web#151]
Add a sentence above Getting Unstuck projects (regular body size): "Click on the name of your project to explore what you made for each prompt."

<img width="664" alt="Screenshot 2020-07-06 10 38 45" src="https://user-images.githubusercontent.com/5756274/86605580-e0fcd900-bf74-11ea-84b7-9822b1c216f0.png">

https://gettingunstuck.gse.harvard.edu/user/mizzpeters

**Comment by azhou4** [comment]
<img width="1436" alt="Screen Shot 2020-07-06 at 6 36 41 pm" src="https://user-images.githubusercontent.com/31658336/86659995-5342dd00-bfb8-11ea-9386-a20cded251c8.png">
https://github.com/GSE-CCL/getting-unstuck-web/commit/bcbb584d7d26c4f51cd96d2000ffa91669788674
