### ISSUE TITLE
Prompts page visual bugs

### ISSUE THREAD

**Issue by paulinahaduong** [GSE-CCL/getting-unstuck-web#158]
- [ ] Button is the wrong color?

- [ ] The columns have gone in the wrong direction!

<img width="977" alt="Screenshot 2020-07-07 06 54 41" src="https://user-images.githubusercontent.com/5756274/86770483-c4b57680-c01e-11ea-85e4-2ce43b6ee707.png">

**Comment by jsarchibald** [comment]
Should be fixed by #164
