### ISSUE TITLE
Title Case + username search problems

### ISSUE THREAD

**Issue by paulinahaduong** [GSE-CCL/getting-unstuck-web#159]
- [ ] MrQuentin
- [ ] MissMissShelly

**Comment by paulinahaduong** [comment]
Bradley wasn't able to pull up his own project; the search feature also didn't work but the project is in the studio?

<img width="613" alt="Screenshot 2020-07-07 08 47 34" src="https://user-images.githubusercontent.com/5756274/86783611-8c1d9900-c02e-11ea-9976-a884db8e1888.png">
<img width="284" alt="Screenshot 2020-07-07 08 47 43" src="https://user-images.githubusercontent.com/5756274/86783612-8cb62f80-c02e-11ea-8861-2e884f0a8f87.png">

**Comment by paulinahaduong** [comment]
Had the same issue w/ MissMissShelly

**Comment by jsarchibald** [comment]
Fixed by #164
