### ISSUE TITLE
Day One: empty inspiration projects?

### ISSUE THREAD

**Issue by paulinahaduong** [GSE-CCL/getting-unstuck-web#160]
Both @karen and I are having this issue?

<img width="953" alt="Screenshot 2020-07-07 09 02 01" src="https://user-images.githubusercontent.com/5756274/86785417-9a6cb480-c030-11ea-856e-d5f55c16ad94.png">

**Comment by laurakpeters** [comment]
![Screen Shot 2020-07-07 at 9 22 37 AM](https://user-images.githubusercontent.com/61284048/86788348-1288a980-c034-11ea-9fd1-efca8a69ac15.png)

**Comment by laurakpeters** [comment]
![Screen Shot 2020-07-07 at 9 27 50 AM](https://user-images.githubusercontent.com/61284048/86788416-23391f80-c034-11ea-9563-51e4beeb6cae.png)

**Comment by laurakpeters** [comment]
![Screen Shot 2020-07-07 at 9 28 54 AM](https://user-images.githubusercontent.com/61284048/86788537-482d9280-c034-11ea-9f41-97a16aa5fea3.png)

**Comment by laurakpeters** [comment]
![Screen Shot 2020-07-07 at 9 29 21 AM](https://user-images.githubusercontent.com/61284048/86788591-58de0880-c034-11ea-8a97-32c6548fdb8e.png)

**Comment by paulinahaduong** [comment]
We also know this is happening w/ @echristophy right now - I think it's a problem w/ the "when stage clicked" block and how it's rendering? The issue vanished when we removed "when stage clicked" from the schema (as in, no more empty inspiration projects) BUT it's not displaying "when stage clicked" blocks at all...

**Comment by jsarchibald** [comment]
Should be fixed now (tested with three projects)
