### ISSUE TITLE
Admin panel viewable at odd times?

### ISSUE THREAD

**Issue by paulinahaduong** [GSE-CCL/getting-unstuck-web#162]
The admin bar was viewable for Amy, Paulina, and Karen on the homepage for awhile (publicly) and then vanished...at odd times it seems to pop up. It's not functional - it asks you to login, but still not ideal, and hard to replicate consistently!
<img width="1186" alt="Screenshot 2020-07-07 10 51 40" src="https://user-images.githubusercontent.com/5756274/86799346-d8bda000-c03f-11ea-92c6-56121525553f.png">

**Comment by paulinahaduong** [comment]
![Screen Shot 2020-07-07 at 10 49 30 AM](https://user-images.githubusercontent.com/5756274/86799780-4d90da00-c040-11ea-84b4-f70d684c92d1.png)

@jsarchibald is this just the cache-ing problem?

**Comment by jsarchibald** [comment]
Should be fixed by caching update
