### ISSUE TITLE
Weird font for "C"

### ISSUE THREAD

**Issue by paulinahaduong** [GSE-CCL/getting-unstuck-web#163]
"Colorful Water Circles"

<img width="412" alt="Screenshot 2020-07-07 11 05 05" src="https://user-images.githubusercontent.com/5756274/86801183-c0e71b80-c041-11ea-9268-faa7f0633b3b.png">
<img width="416" alt="Screenshot 2020-07-07 11 05 11" src="https://user-images.githubusercontent.com/5756274/86801185-c17fb200-c041-11ea-9659-b1ac750a8b96.png">
https://scratch.mit.edu/projects/409906692

**Comment by paulinahaduong** [comment]
Update: pretty sure it's a Unicode Cyrillic alphabet issue (low priority)

**Comment by jsarchibald** [comment]
Is this really something we want to attempt to fix? Our font doesn't support the Cyrillic alphabet, and converting all Cyrillic characters might cause an issue if the user has a valid reason to use them?

**Comment by paulinahaduong** [comment]
I labelled it a "wontfix"; just good to document! (if it's a wontfix should we still close it...? just leave it open + lingering?)

**Comment by jsarchibald** [comment]
I think we can close it, it's always documented in closed issues
