### ISSUE TITLE
"key" scratch block not visible?

### ISSUE THREAD

**Issue by paulinahaduong** [GSE-CCL/getting-unstuck-web#165]
<img width="122" alt="Screenshot 2020-07-07 11 47 01" src="https://user-images.githubusercontent.com/5756274/86810923-62269f80-c04b-11ea-99e2-689e44c8a883.png">
<img width="288" alt="Screenshot 2020-07-07 12 14 44" src="https://user-images.githubusercontent.com/5756274/86811035-7a96ba00-c04b-11ea-984d-5235cbcc5c12.png">

"forever
 if <key (down arrow v) pressed?> then
 change y by (-10)" <-- this isn't rendering on the studio page?

**Comment by paulinahaduong** [comment]
<img width="450" alt="Screenshot 2020-07-07 12 17 07" src="https://user-images.githubusercontent.com/5756274/86811330-c9445400-c04b-11ea-96bc-89bddecb55fe.png">

the fact that "key" highlights in yellow makes me think that it's being read as some other kind of tag?

**Comment by jsarchibald** [comment]
Hmmm... <key > I don't think is valid scratchblocks; I think it looks for the full statement Have you tried: <key [ v] pressed?>

**Comment by jsarchibald** [comment]
[sb]key [ v] pressed?[/sb] seems to work here where <key > is

**Comment by paulinahaduong** [comment]
That worked! but not when I wanted to create a stack...

`<code class="_sb">forever 
if key (down arrow) pressed? then
 change y by (-10)</code>`

<img width="270" alt="Screenshot 2020-07-07 13 31 06" src="https://user-images.githubusercontent.com/5756274/86819791-26450780-c056-11ea-8920-e71146204ebb.png">

**Comment by jsarchibald** [comment]
Found this to work (using HTML codes for `<>`:
```
[_sb]forever 
if &lt;key [down arrow v] pressed?&gt; then
 change y by (-10)[/_sb]
```

Also added `[_sb]` which will do a stack, as opposed to inline `[sb]`

**Comment by paulinahaduong** [comment]
Amazing, thank you!!!

**Comment by paulinahaduong** [comment]
Also you're a genius - I should've thought of that!

**Comment by jsarchibald** [comment]
Marking this as closed since I think it was resolved!
