### ISSUE TITLE
"broadcast" schema not working...only for mizzpeters?

### ISSUE THREAD

**Issue by paulinahaduong** [GSE-CCL/getting-unstuck-web#176]
<img width="740" alt="Screenshot 2020-07-10 11 42 24" src="https://user-images.githubusercontent.com/5756274/87172661-9051ec80-c2a2-11ea-8134-1e2bde953bb9.png">
<img width="874" alt="Screenshot 2020-07-10 11 42 33" src="https://user-images.githubusercontent.com/5756274/87172663-90ea8300-c2a2-11ea-8e2b-ea5ed985c228.png">

I assumed that something was wrong with the way I created the schema so I tried a couple different iterations of required blocks (grouping broadcast + wait w/ when I received | broadcast + when I received)...at the moment it is currently just looking for **broadcast and wait** OR **broadcast** OR **when I received** (not ideal, but good enough). 

Only LP's project seems to not be working? Sometimes it appears...but other times it seems to break. Other projects are continuing to show "when I received" blocks...is it because the stack is long? What else might be happening?

**Comment by jsarchibald** [comment]
The translate_getTranslate block handler was placed in the wrong part of scratch-to-blocks -- will fix

**Comment by jsarchibald** [comment]
Fixed some similar issues with extensions having the wrong scratchblocks syntax; this should hopefully prevent future rendering issues

**Comment by jsarchibald** [comment]
Took some work but should be fixed, will update ccl_scratch_tools version on servers:
![image](https://user-images.githubusercontent.com/43184986/87183788-cbf5b200-c2b4-11ea-8680-1fbae9843cfb.png)
