### ISSUE TITLE
Page <title>s should be updated to reflect the page content

### ISSUE THREAD

**Issue by kbrennan** [GSE-CCL/getting-unstuck-web#180]
The titles of three pages seem misaligned from the content of those pages. Here are the three pages and their proposed updated text. Thank you!

- [ ] Strategies page <title> is "Welcome &minus; Getting Unstuck" should be "Strategies &minus; Getting Unstuck" https://gettingunstuck.gse.harvard.edu/strategies

- [ ] About page <title> is "Welcome &minus; Getting Unstuck" should be "About &minus; Getting Unstuck" https://gettingunstuck.gse.harvard.edu/about

- [ ] Signup page <title> is "Getting Unstuck" should be "Sign Up &minus; Getting Unstuck" https://gettingunstuck.gse.harvard.edu/signup

**Comment by azhou4** [comment]
pushed to master! #182
