### ISSUE TITLE
About page is missing funding attribution

### ISSUE THREAD

**Issue by kbrennan** [GSE-CCL/getting-unstuck-web#181]
Could we please add another paragraph to the bottom of the "Who are you?" question (after "and Laura Peters", but before the video) on [the About page](https://gettingunstuck.gse.harvard.edu/about) to acknowledge the funding support?

Here's the (NSF-required) text:
This material is based upon work supported by the National Science Foundation under Grant No. 1908110 and by Siegel Family Endowment. Any opinions, findings, and conclusions or recommendations expressed in this material are those of the author(s) and do not necessarily reflect the views of the National Science Foundation or of Siegel Family Endowment.

**Comment by azhou4** [comment]
Pushed to master #183 !
