### ISSUE TITLE
Remove "summary" from navbar

### ISSUE THREAD

**Issue by paulinahaduong** [GSE-CCL/getting-unstuck-web#192]
KB and I would like it removed from the navbar, thank you!

<img width="379" alt="Screenshot 2020-07-18 06 14 28" src="https://user-images.githubusercontent.com/5756274/87851402-54cca900-c8c6-11ea-999c-6e989b6c0804.png">

**Comment by azhou4** [comment]
#196 
<img width="1437" alt="Screen Shot 2020-07-18 at 9 45 54 am" src="https://user-images.githubusercontent.com/31658336/87853897-eeeb1c00-c8db-11ea-942e-629efdf6f98e.png">
