### ISSUE TITLE
Change index.html links from white to just black underline

### ISSUE THREAD

**Issue by paulinahaduong** [GSE-CCL/getting-unstuck-web#193]
Or maybe blue? (whatever the original color was) right now they pop too much

<img width="418" alt="Screenshot 2020-07-18 07 18 50" src="https://user-images.githubusercontent.com/5756274/87851456-f05e1980-c8c6-11ea-8b3e-83f785825009.png">

**Comment by kbrennan** [comment]
I think it was blue, but I'm sure @azhou4 knows!

**Comment by azhou4** [comment]
#196 
<img width="1437" alt="Screen Shot 2020-07-18 at 9 45 54 am" src="https://user-images.githubusercontent.com/31658336/87853879-d549d480-c8db-11ea-8b05-21e2258452f2.png">

**Comment by jsarchibald** [comment]
I know this is closed, but they were appearing as the same blue as the background, which is why I changed them to white! But glad this is resolved.

**Comment by azhou4** [comment]
Yes! I noticed that too, and I changed it to a class that I used previously (i think) for links to get around that issue.

**Comment by jsarchibald** [comment]
I think it looks great now @azhou4!

**Comment by azhou4** [comment]
thanks :)
