### ISSUE TITLE
Add date stamp to summary page

### ISSUE THREAD

**Issue by paulinahaduong** [GSE-CCL/getting-unstuck-web#194]
Please add in the same small body styling w/ italics above the "Dear friends", a date stamp: "Last updated Saturday, July 18, 2020"

<img width="411" alt="Screenshot 2020-07-18 09 13 19" src="https://user-images.githubusercontent.com/5756274/87853294-ee9c5200-c8d6-11ea-8932-d6c5a9f4903a.png">

**Comment by azhou4** [comment]
#196 
![Uploading Screen Shot 2020-07-18 at 9.46.08 am.png…]()

**Comment by azhou4** [comment]
<img width="694" alt="Screen Shot 2020-07-18 at 9 46 08 am" src="https://user-images.githubusercontent.com/31658336/87853885-dda20f80-c8db-11ea-8a65-f7080c5b3277.png">

**Comment by jsarchibald** [comment]
I went a step further and made this auto-generate every time you Generate summary page under utilities. See #197

**Comment by paulinahaduong** [comment]
You’re amazing! I figured I’d ask for that down the line but you did it!

-- 
Paulina Haduong
