### ISSUE TITLE
Update the About page to add Priya

### ISSUE THREAD

**Issue by paulinahaduong** [GSE-CCL/getting-unstuck-web#195]
"The Getting Unstuck summer 2020 experience has also been made possible with the support of members of the Creative Computing Lab: Joshua Archibald, Amy Zhou, and Laura Peters." 

becomes

"The Getting Unstuck summer 2020 experience has also been made possible with the support of members of the Creative Computing Lab: Joshua Archibald, Amy Zhou, and Laura Peters. Special thanks to Priya Vetrimani, Associate Director of Infrastructure Technologies at the Harvard Graduate School of Education, for her abundantly generous support."

**Comment by azhou4** [comment]
#196 
<img width="1414" alt="Screen Shot 2020-07-18 at 9 45 46 am" src="https://user-images.githubusercontent.com/31658336/87853901-f90d1a80-c8db-11ea-8e04-28ef2d0766fc.png">
