### ISSUE TITLE
Add Google Analytics

### ISSUE THREAD

**Issue by jsarchibald** [GSE-CCL/getting-unstuck-web#24]
Including action trackers, e.g. how many comparison projects do they actually look at?

**Comment by kbrennan** [comment]
`
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-121701097-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-121701097-1');
</script>
`
