### ISSUE TITLE
Prompts page edits

### ISSUE THREAD

**Issue by paulinahaduong** [GSE-CCL/getting-unstuck-web#39]
- [ ] More white space between the prompt text and the blue border (the white space below "see the email" and "explore the Scratch studio" looks good; add margin to match the bottom around the top/left/right)
- [ ] Noting that in @jsarchibald schema the "short description" was "Day 1"; can we make sure that only the number appears here?

**Comment by azhou4** [comment]
There's currently a uniform 12px margin, equal around everything. I think it might be an illusion that there is less margin top/left/right. Do you want to me to add more margins there anyway?
![Screen Shot 2020-06-22 at 11 05 06 pm](https://user-images.githubusercontent.com/31658336/85356378-d1918080-b4dc-11ea-86d1-b06e149a3434.png)

**Comment by azhou4** [comment]
@jsarchibald is the "short label" of the schema meant to address the second point? If so, I can connect the prompt day # to the "short label" input on the schema.

**Comment by jsarchibald** [comment]
Yeah, I would think it's probably fine to just do `{{ schema["short_label"] }}` -- it's not used anywhere on the result page, so they can set it to be just a number in the schema.

**Comment by paulinahaduong** [comment]
@azhou4 Weird! It definitely looked smaller in the screenshot, but if it's even I guess it's even. :)

**Comment by paulinahaduong** [comment]
I think what's actually causing the visual confusion is the "p" in explore - it adds white space under the "see the email" blue text...maybe to resolve this, what if the bottom margin was only 8 or 10px?

**Comment by azhou4** [comment]
Sure, can do! Here is 8px. 

![Screen Shot 2020-06-23 at 8 55 33 pm](https://user-images.githubusercontent.com/31658336/85484005-ee3cbf80-b593-11ea-96eb-6b63b2005f04.png)

**Comment by paulinahaduong** [comment]
I think that looks a lot better - thank you for the visual trickery help!

(can we halve the white space between the text "every day..." and the table?

**Comment by azhou4** [comment]
Done! #78
