### ISSUE TITLE
Username submission page

### ISSUE THREAD

**Issue by paulinahaduong** [GSE-CCL/getting-unstuck-web#41]
- [ ] Two column layout; all of the text in one column; image on the right. (see below)
- [ ] Maybe it's weird...can we center the SUBMIT button (in the left column)?

![site-page](https://user-images.githubusercontent.com/5756274/85233143-40ce7e00-b3d2-11ea-8a2f-9e952708c8bc.png)

**Comment by azhou4** [comment]
![Screen Shot 2020-06-22 at 11 28 35 pm](https://user-images.githubusercontent.com/31658336/85357769-1a970400-b4e0-11ea-9238-748493d5be1f.png)
Is it possible to get a higher resolution version of the image? How do you feel about the centered button?

**Comment by azhou4** [comment]
![Screen Shot 2020-06-22 at 11 31 54 pm](https://user-images.githubusercontent.com/31658336/85357973-909b6b00-b4e0-11ea-9f5c-e670bf144c6f.png)
Better screenshot, correct button color, slightly smaller image as a comparison

**Comment by paulinahaduong** [comment]
Okay, the submit button just looks bad centered (sorry) - what if we put it right next to the username fill-in box?

**Comment by paulinahaduong** [comment]
And do you still need a higher res image @azhou4 ?
