### ISSUE TITLE
personal project list

### ISSUE THREAD

**Issue by paulinahaduong** [GSE-CCL/getting-unstuck-web#42]
- [x] Let's also do a 2 column layout here? See below for image on the right.
![get-unstuckm copy 5](https://user-images.githubusercontent.com/5756274/85233398-d3235180-b3d3-11ea-9856-94072f3e1464.png)

- [x] "jsarchibald": change that to "jsarchibald's projects", use the Gastromond title font style, and center it
- [x] "view user on Scratch" - center that under the title as "view Scratch profile"
- [x] "view user on Scratch" -- same font size as "here are all of the getting unstuck"
- [x] "Here are all of the Getting Unstuck projects by jsarchibald:" --> "Getting Unstuck projects:" (keep the bold)
- [x] Font size for "day 2: flowers..." >> same font size as "here are all of the getting unstuck" (just one body font, hopefully?)
- [x] "Is there a project missing..." unbold, do the small font of "view user on Scratch"

**Comment by azhou4** [comment]
![Screen Shot 2020-06-22 at 11 45 25 pm](https://user-images.githubusercontent.com/31658336/85358721-7498c900-b4e2-11ea-82d9-c067f2ceeadc.png)
I agree the font sizes look different, but I checked and I'm pretty sure they are all 16px...super weird! 

![Screen Shot 2020-06-22 at 11 46 13 pm](https://user-images.githubusercontent.com/31658336/85358777-91350100-b4e2-11ea-8c3a-23a0b68e1ffa.png)
For items #2 and #3, I wasn't sure if you wanted to keep them in the left column, or centered overall. Let me know what you think!

**Comment by paulinahaduong** [comment]
I think this looks a lot better! Can we: 

- [ ] move the bullets to the far left so they're aligned w/ everything else
- [ ] make the image maybe 1/3, so that the names of projects are more likely to all be on one line?
- [ ] Maybe halve the white space between the project and the "Is there a project"? 
- [ ] Jus tto confirm - the "in studio Getting Unstuck" takes you to Scratch...right?

**Comment by azhou4** [comment]
done! #59 I changed to a 7:5 column ratio. 8:4 or 9:3 would make the image too small. 
Yes, the studio link takes you to the scratch website. 

![Screen Shot 2020-06-23 at 10 43 56 pm](https://user-images.githubusercontent.com/31658336/85492349-08ca6500-b5a3-11ea-8023-086f1401e142.png)

**Comment by azhou4** [comment]
The screenshot makes it look like there is a lot of space (column wise) but remember there's 960px total and also disclaimer: screenshot taken on monitor (sorry!)

**Comment by azhou4** [comment]
@paulinahaduong just confirming if this looks ok?

**Comment by paulinahaduong** [comment]
Yes - it's beautiful!

**Comment by azhou4** [comment]
Yay awesome! Closing issue now
