### ISSUE TITLE
Changing comparative text labeling on the schema

### ISSUE THREAD

**Issue by paulinahaduong** [GSE-CCL/getting-unstuck-web#44]
- [x] "Project Comparisons" >> "Projects to Inspire"
- [x] "Comparison basis" >> "Ways to find inspiration projects"
- [x] "We can search for comparison projects based on..." >> "We can search for inspiration projects based on..."
- [x] "Comparison framing text" >> "Inspiration framing text"
- [x] "Comparison reflection text" >> "Inspiration reflection text"

**Comment by jsarchibald** [comment]
@paulinahaduong Is "How to find inspiration projects" fine? Because you only choose one, so "ways" might be a bit confusing.

**Comment by paulinahaduong** [comment]
> @paulinahaduong Is "How to find inspiration projects" fine? Because you only choose one, so "ways" might be a bit confusing.

That makes sense to me! :)

**Comment by jsarchibald** [comment]
Resolved by 8e5084489abd504672f79c0127a27e0496bc759b
