### ISSUE TITLE
project summary page: title

### ISSUE THREAD

**Issue by paulinahaduong** [GSE-CCL/getting-unstuck-web#45]
- [x] Update the title "2018 - Day 1" to the title style (e.g., "About" on https://gettingunstuck.gse.harvard.edu/about.html), which is larger. 

Question: "2018 - Day 1" is just the current title of the schema, right? If we change that title this will automatically update?

**Comment by azhou4** [comment]
Yes "2018 - Day 1" is just the title of the prompt! Can be changed.
