### ISSUE TITLE
Vertical spacing for text above the first (your project) font excerpt)

### ISSUE THREAD

**Issue by paulinahaduong** [GSE-CCL/getting-unstuck-web#47]
Adjust spacing between all of the framing text and blocks to be more even. The spacing above and below the Scratch blocks should match (in general, the margin/padding above is closer to what we're looking for). Less space between the "here's an example of..." and the code excerpt (similar to the "Now that we've looked at...")

Basically, wherever we can, make the spacing a little smaller.

Q: Is "here's an example of how you used the Touching Object block..." still automated? If so (that's what I last recalled); can we just append it to the end of the previous framing text?

**Comment by azhou4** [comment]
See https://github.com/GSE-CCL/getting-unstuck-web/commit/cd1b6d66b4e5d880d3a22d656879200309ce9ee3
I did this kind of blindly (will update during Thursday meeting) but hopefully Josh can show via demo what it looks like. 

`<p class="text-center">
                Here&rsquo;s an example of how you used
                <strong>{{ schema["comparison_basis"]["priority"] }}</strong>
                blocks in
                <a href="https://scratch.mit.edu/projects/{{ project['project_id'] }}" target="_blank">your project</a>:
            </p>`
Yes the block part in that sentence is automated!
