### ISSUE TITLE
navbar changes

### ISSUE THREAD

**Issue by paulinahaduong** [GSE-CCL/getting-unstuck-web#67]
- [ ] Hamburger should be right aligned and in-line w/ the logo (OR, get rid of the hamburger and just have the nav items stack)

- [x] Nav bar should include: STRATEGIES

- [x] Nav bar should include: ABOUT

- [x] Nav bar should include: SIGN UP

- [ ] Nav bar should be consistent across all pages.

- [x] Everything in Navbar should be all caps

- [ ] Everything in Navbar should be 0.7rem not 1 rem

- [ ] The hamburger doesn't work? Nothing drops down?

**Comment by azhou4** [comment]
@paulinahaduong no "PROMPTS" in Nav Bar?

**Comment by azhou4** [comment]
@paulinahaduong also 0.7rem = 11.2px, are you sure you want 0.7rem?
![Screen Shot 2020-06-25 at 5 18 42 pm](https://user-images.githubusercontent.com/31658336/85796443-f61d7080-b707-11ea-8ba7-8559071cecb8.png)

**Comment by azhou4** [comment]
@paulinahaduong have you found any inconsistencies with the navbar? right now it is a layout, so it should be consistent across all pages, unless you found something weird.

**Comment by paulinahaduong** [comment]
I haven't, I was just adding it as a reminder that it should be consistent across all pages. :)

**Comment by paulinahaduong** [comment]
okay i'm willing to do 1rem IF there's more space (3-5px) between each word? And the Login tab will be hidden, right?

**Comment by paulinahaduong** [comment]
> @paulinahaduong no "PROMPTS" in Nav Bar?

OOPS good catch! Let's do PROMPTS.  STRATEGIES.   ABOUT.   SIGNUP (?)

**Comment by azhou4** [comment]
hmm @jsarchibald can you confirm the "LOGIN" is hidden? the code says yes, but it's always shown for me (probably since I'm a user)

**Comment by azhou4** [comment]
<img width="1422" alt="Screen Shot 2020-06-25 at 6 34 28 pm" src="https://user-images.githubusercontent.com/31658336/85802239-8cef2a80-b712-11ea-992a-2450843fc102.png">
new and improved!

**Comment by paulinahaduong** [comment]
Minus the login of course, it looks great!!

-- 
Paulina Haduong

**Comment by jsarchibald** [comment]
@azhou4 the login stuff is here -- https://github.com/GSE-CCL/getting-unstuck-web/blob/master/templates/layout.html#L41

The "if not user" logic is to determine whether currently logged in (which is why it still shows up). I think @paulinahaduong wants us to remove the link altogether from the nav bar--so removing lines 41-43. I'd suggest adding it to a new footer in layout.html though, renaming the link "Admin login", because I hate the idea of having to type out the link to login. It's just a pain.

**Comment by azhou4** [comment]
@jsarchibald ok yeah I saw that, I can go ahead and delete it, it's foolproof I guess.

**Comment by paulinahaduong** [comment]
@jsarchibald @azhou4 I definitely recognize that typing out the link to log in is a pain, BUT the priority is the user experience of participants. @kbrennan and I would prefer the login link to be hidden altogether, thank you!
