### ISSUE TITLE
index.html bugs

### ISSUE THREAD

**Issue by paulinahaduong** [GSE-CCL/getting-unstuck-web#69]
- [ ] Button to "Sign Up for Getting Unstuck!" is broken (needs dark grey text on grey background)

- [x] Update main text on index.html 

<img width="355" alt="Screenshot 2020-06-25 11 31 55" src="https://user-images.githubusercontent.com/5756274/85750213-7f687f00-b6d7-11ea-8110-6ca4f99ea1d7.png">
<img width="255" alt="Screenshot 2020-06-25 11 32 00" src="https://user-images.githubusercontent.com/5756274/85750215-80011580-b6d7-11ea-8223-1cf6ec63da95.png">

```<div class="six columns" id="splash-page">
        <h4>Getting Unstuck</h4>

        <p><strong>JULY 6-17, 2020</strong></p>
        <p><em>10 days. 10 Scratch projects. What will you make?</em></p>

        <p>Dear friends,</p>
        <p> Supporting creative work in the classroom can be challenging, and we want to help! We're excited to offer Getting Unstuck, a summer learning experience for teachers who want to learn more about supporting creative work with the Scratch programming language.</p>

        <p>Every day, you'll get an email with a small, creative programming prompt, designed to help you explore different computational concepts and debugging strategies in Scratch. You'll have access to a supportive <a href="https://www.facebook.com/groups/GettingUnstuckCommunity/" target=”_blank”>online community</a> of teachers and facilitators. Whether you're brand new to Scratch or an experienced teacher, we'll be right beside you, making things and learning together.</p>

		<p>Yours in creative computing,
			<br/>Paulina and Karen</p>


    </div>
```

**Comment by azhou4** [comment]
![Screen Shot 2020-06-25 at 5 59 26 pm](https://user-images.githubusercontent.com/31658336/85799678-9de96d00-b70d-11ea-86ff-0c5c5283e9cc.png)
Fixed! https://github.com/GSE-CCL/getting-unstuck-web/commit/25e98653b0be5d058ba59ca1189817a6a3864bea

**Comment by paulinahaduong** [comment]
@azhou4 I know I might be asking for too much... can we get Steven to be vertically center-aligned as well? and is this a monitor screenshot? (the text seems large...?)

**Comment by azhou4** [comment]
<img width="1426" alt="Screen Shot 2020-06-25 at 6 42 48 pm" src="https://user-images.githubusercontent.com/31658336/85802803-b0ff3b80-b713-11ea-9023-b8e883b4c916.png">
@paulinahaduong steven is now centered! this screenshot is on my laptop

**Comment by azhou4** [comment]
The font size is slightly larger than 2018's website (17px versus ~14px). Should I change it?

**Comment by paulinahaduong** [comment]
Yes let’s do 14px thanks!

-- 
Paulina Haduong

**Comment by azhou4** [comment]
Done!
