### ISSUE TITLE
Studio download says "in progress" although there are no downloads

### ISSUE THREAD

**Issue by azhou4** [GSE-CCL/getting-unstuck-web#7]
![Screen Shot 2020-06-03 at 10 06 03 pm](https://user-images.githubusercontent.com/31658336/83706800-6c85f180-a5e6-11ea-9689-6a95f06ce6a4.png)

When downloading a studio, there are no errors whatsoever, but no projects seem to download even after refreshing several minutes later.

**Comment by jsarchibald** [comment]
Which studio is this? If there's no convert server running, then any SB2 projects -- which many of the 2018 studios are mostly SB2 -- will be skipped, which is likely why nothing is downloaded.

**Comment by jsarchibald** [comment]
Ran a test on the studio with and without convert server running. Appears this studio was just overwhelmingly SB2 projects. Use [scratch-convert](https://github.com/gse-ccl/scratch-convert) as by running `node app.js` and changing `CONVERT_URL` to `http://localhost:3000/convert` in `settings.py` (in the latest version on `master`).
