### ISSUE TITLE
strategies.html

### ISSUE THREAD

**Issue by paulinahaduong** [GSE-CCL/getting-unstuck-web#70]
What is happening with this page? Can we get it to look like the [live version](https://gettingunstuck.gse.harvard.edu/strategies.html )?

(Let me know if you want help working on this!)

**Comment by paulinahaduong** [comment]
@azhou4 It looks like part of what is broken is the flexbox options are just labeled differently in skeleton.css v. boostrap? 

https://getbootstrap.com/docs/4.0/utilities/flex/ 
http://getskeleton.com/

**Comment by azhou4** [comment]
![Screen Shot 2020-06-25 at 5 44 35 pm](https://user-images.githubusercontent.com/31658336/85798480-8b6e3400-b70b-11ea-89aa-758fa88aa600.png)
My bad! Fixed now. The strategies.css file somehow was no longer included. https://github.com/GSE-CCL/getting-unstuck-web/commit/3f31d4447c982d7da044ae92c23d7ac2bbc64bc6
