### ISSUE TITLE
h4

### ISSUE THREAD

**Issue by paulinahaduong** [GSE-CCL/getting-unstuck-web#71]
- [ ] It looks like right now h4 is set (across the site) to 1.5rem; can we change that to 2rem?

- [ ] Minimize spacing between navbar and h4. (first two screenshots are from live site; third is from dev).

<img width="405" alt="Screenshot 2020-06-25 11 42 02" src="https://user-images.githubusercontent.com/5756274/85751942-f9e5ce80-b6d8-11ea-9eb0-589d89f83624.png">
<img width="323" alt="Screenshot 2020-06-25 11 42 06" src="https://user-images.githubusercontent.com/5756274/85751943-fa7e6500-b6d8-11ea-81d6-669de0848eb5.png">
<img width="368" alt="Screenshot 2020-06-25 11 42 11" src="https://user-images.githubusercontent.com/5756274/85751944-fa7e6500-b6d8-11ea-91cf-abc76d4c4dd9.png">

**Comment by azhou4** [comment]
done! #79 

<img width="1421" alt="Screen Shot 2020-06-25 at 6 50 22 pm" src="https://user-images.githubusercontent.com/31658336/85803259-bb6e0500-b714-11ea-9c3f-38d798a12fc0.png">
