### ISSUE TITLE
project summary page - increase white space between code excerpt and the sprite

### ISSUE THREAD

**Issue by paulinahaduong** [GSE-CCL/getting-unstuck-web#83]
Can we create more whitespace between the sprite and the code excerpt? I think it'll mean moving the code excerpt more to the left and moving the sprite a little to the right (add at least as much space as between code excerpt and the tabs.

**Comment by azhou4** [comment]
![Screen Shot 2020-06-28 at 8 08 02 pm](https://user-images.githubusercontent.com/31658336/85961830-130daa00-b97b-11ea-8328-a30e9d8d1b1c.png)
![Screen Shot 2020-06-28 at 8 08 14 pm](https://user-images.githubusercontent.com/31658336/85961836-1a34b800-b97b-11ea-8891-95d7fa3dabcc.png)
Is this enough? I tried adding more, and it looked a bit off center: (see below)
![Screen Shot 2020-06-28 at 8 08 58 pm](https://user-images.githubusercontent.com/31658336/85961855-35072c80-b97b-11ea-888f-0eb3073634fe.png)

**Comment by paulinahaduong** [comment]
Hmm I think it's okay? We can doublecheck w/ KB today.

Also we should doublecheck about rounded v. non-rounded corners, hah!

**Comment by azhou4** [comment]
@paulinahaduong oops we forgot to doublecheck
