### ISSUE TITLE
strategies.html

### ISSUE THREAD

**Issue by paulinahaduong** [GSE-CCL/getting-unstuck-web#84]
Can we make the space the same, vertical as it is horizontal? (i.e., narrow the spacing between the rows)

I assume that some kind of randomization is still happening?

**Comment by azhou4** [comment]
![Screen Shot 2020-06-28 at 7 15 56 pm](https://user-images.githubusercontent.com/31658336/85960732-ce324500-b973-11ea-8cd1-0fab0a978105.png)
Fixed!
