### ISSUE TITLE
project summary page - grey border for tabs

### ISSUE THREAD

**Issue by paulinahaduong** [GSE-CCL/getting-unstuck-web#86]
light grey + thin, all the way around each tab?

**Comment by azhou4** [comment]
Not a super fan of the border, but I think the second one is ok?
![Screen Shot 2020-06-28 at 8 11 25 pm](https://user-images.githubusercontent.com/31658336/85961891-95966980-b97b-11ea-8e26-ff14bfb95287.png)
![Screen Shot 2020-06-28 at 8 12 19 pm](https://user-images.githubusercontent.com/31658336/85961902-ae068400-b97b-11ea-8713-7a6d8d6ded2d.png)

**Comment by paulinahaduong** [comment]
Hmm I agree that the border looks not great (definitely better w/ gray then w/ black - what about a lighter gray? Or a black vertical line that is just half as long (and centered)

<img width="368" alt="Screenshot 2020-06-29 08 23 33" src="https://user-images.githubusercontent.com/5756274/86004985-0cfee400-b9e2-11ea-9b0b-abf490fd344d.png">
<img width="269" alt="Screenshot 2020-06-29 08 23 45" src="https://user-images.githubusercontent.com/5756274/86004990-0d977a80-b9e2-11ea-96ba-f18f4ddf97c1.png">
