### ISSUE TITLE
tabs! colors!

### ISSUE THREAD

**Issue by paulinahaduong** [GSE-CCL/getting-unstuck-web#97]
Hi Amy,

We settled on tab colors! See attached. (the one with the red box around them)
<img width="934" alt="Screenshot 2020-06-29 14 15 57" src="https://user-images.githubusercontent.com/5756274/86041116-2bc99e80-ba13-11ea-979a-6f6694f38a83.png">

[website_prototype_tabs.ai.zip](https://github.com/GSE-CCL/getting-unstuck-web/files/4847312/website_prototype_tabs.ai.zip)

**Comment by azhou4** [comment]
![Screen Shot 2020-06-29 at 9 36 27 pm](https://user-images.githubusercontent.com/31658336/86072867-9947f000-ba50-11ea-8d6b-2ed27dca92d1.png)
done!
